# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: files.proto for package 'Files'

require 'grpc'
require 'files_pb'

module Files
  module RpcServer
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'Files.RpcServer'

      rpc :UploadFileClientStream, stream(::Files::UploadFileRequest), ::Files::UploadFileResponse
      rpc :GetFile, ::Files::GetFileRequest, ::Files::GetFileResponse
      rpc :DeleteFile, ::Files::DeleteFileRequest, ::Files::DeleteFileResponse
    end

    Stub = Service.rpc_stub_class
  end
end
