# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files.proto

require 'google/protobuf'


descriptor_data = "\n\x0b\x66iles.proto\x12\x05\x46iles\"F\n\x0eGetFileRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\nremote_url\x18\x02 \x01(\x08\x12\x14\n\x0c\x64ownload_url\x18\x03 \x01(\x08\"\x7f\n\x0fGetFileResponse\x12\x12\n\nremote_url\x18\x01 \x01(\t\x12\x14\n\x0c\x64ownload_url\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x15\n\rerror_message\x18\x05 \x01(\t\x12\x0c\n\x04name\x18\x06 \x01(\t\"\x1f\n\x11\x44\x65leteFileRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"<\n\x12\x44\x65leteFileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\"$\n\x11UploadFileRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"f\n\x12UploadFileResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nremote_url\x18\x03 \x01(\t\x12\x14\n\x0c\x64ownload_url\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t2\xdd\x01\n\tRpcServer\x12O\n\x16UploadFileClientStream\x12\x18.Files.UploadFileRequest\x1a\x19.Files.UploadFileResponse(\x01\x12:\n\x07GetFile\x12\x15.Files.GetFileRequest\x1a\x16.Files.GetFileResponse\"\x00\x12\x43\n\nDeleteFile\x12\x18.Files.DeleteFileRequest\x1a\x19.Files.DeleteFileResponse\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Files
  GetFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Files.GetFileRequest").msgclass
  GetFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Files.GetFileResponse").msgclass
  DeleteFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Files.DeleteFileRequest").msgclass
  DeleteFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Files.DeleteFileResponse").msgclass
  UploadFileRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Files.UploadFileRequest").msgclass
  UploadFileResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Files.UploadFileResponse").msgclass
end
